name: surflutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^2.0.1+1
  cloud_firestore: 0.12.0
  firestore_ui: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  
  fonts:
    - family: GoogleSans
      fonts:
        - asset: res/fonts/google_sans/GoogleSans-Regular.ttf
        - asset: res/fonts/google_sans/GoogleSans-Italic.ttf
          style: italic
        - asset: res/fonts/google_sans/GoogleSans-Medium.ttf
          weight: 700
        - asset: res/fonts/google_sans/GoogleSans-Bold.ttf
          weight: 900
